### ISSUE TITLE
Error: Apple Mach-O Linker Error Group

### ISSUE THREAD

**Issue by mohsinalimat** [lucyios/IMChat#1]
When i run your code then error comes 'clang: error: linker command failed with exit code 1 (use -v to see invocation)'

**Comment by lucyios** [comment]
en,Because lack of static library of NIMSDk,for example, libNIMSDK.a,libNIMAVChat.a,libssl.a and so on ,you need to download those library from officical website,"http://dev.netease.im/",thank u!

**Comment by yizibi** [comment]
en,Because lack of static library of NIMSDK,like **libNIMSDK.a**,**ibNIMAVChat.a** and so on ,you need to download those library from  [official website](http://dev.netease.im/) ,thank you !
